# Generated by scripts/theme.ts from themes/nord/.

export def fallout-default-variant [] {
  "dark"
}

export def fallout-dark-color-config [] {
    {
      separator: '#8fbcbb'
      leading_trailing_space_bg: { attr: n }
      header: '#88c0d0'
      empty: '#8fbcbb'
      bool: '#88c0d0'
      int: '#eceff4'
      filesize: '#eceff4'
      duration: '#8fbcbb'
      date: '#8fbcbb'
      range: '#8fbcbb'
      float: '#eceff4'
      string: '#eceff4'
      nothing: '#616e82'
      binary: '#eceff4'
      cellpath: '#eceff4'
      row_index: '#88c0d0'
      record: '#eceff4'
      list: '#eceff4'
      block: '#eceff4'
      hints: '#616e82'
      shape_and: '#88c0d0'
      shape_binary: '#88c0d0'
      shape_block: '#88c0d0'
      shape_bool: '#88c0d0'
      shape_custom: '#8fbcbb'
      shape_datetime: '#88c0d0'
      shape_directory: '#88c0d0'
      shape_external: '#88c0d0'
      shape_externalarg: '#88c0d0'
      shape_filepath: '#88c0d0'
      shape_flag: '#88c0d0'
      shape_float: '#88c0d0'
      shape_garbage: { fg: '#88c0d0' bg: '#616e82' attr: b }
      shape_globpattern: '#88c0d0'
      shape_int: '#88c0d0'
      shape_internalcall: '#88c0d0'
      shape_list: '#88c0d0'
      shape_literal: '#8fbcbb'
      shape_matching_brackets: { attr: u }
      shape_nothing: '#88c0d0'
      shape_operator: '#8fbcbb'
      shape_or: '#88c0d0'
      shape_pipe: '#88c0d0'
      shape_range: '#88c0d0'
      shape_record: '#88c0d0'
      shape_redirection: '#88c0d0'
      shape_signature: '#88c0d0'
      shape_string: '#eceff4'
      shape_string_interpolation: '#88c0d0'
      shape_table: '#88c0d0'
      shape_variable: '#8fbcbb'
    }
}

export def fallout-light-color-config [] {
    {
      separator: '#4c7a8a'
      leading_trailing_space_bg: { attr: n }
      header: '#5e81ac'
      empty: '#4c7a8a'
      bool: '#5e81ac'
      int: '#2e3440'
      filesize: '#2e3440'
      duration: '#4c7a8a'
      date: '#4c7a8a'
      range: '#4c7a8a'
      float: '#2e3440'
      string: '#2e3440'
      nothing: '#5e81ac'
      binary: '#2e3440'
      cellpath: '#2e3440'
      row_index: '#5e81ac'
      record: '#2e3440'
      list: '#2e3440'
      block: '#2e3440'
      hints: '#5e81ac'
      shape_and: '#5e81ac'
      shape_binary: '#5e81ac'
      shape_block: '#5e81ac'
      shape_bool: '#5e81ac'
      shape_custom: '#4c7a8a'
      shape_datetime: '#5e81ac'
      shape_directory: '#5e81ac'
      shape_external: '#5e81ac'
      shape_externalarg: '#5e81ac'
      shape_filepath: '#5e81ac'
      shape_flag: '#5e81ac'
      shape_float: '#5e81ac'
      shape_garbage: { fg: '#5e81ac' bg: '#5e81ac' attr: b }
      shape_globpattern: '#5e81ac'
      shape_int: '#5e81ac'
      shape_internalcall: '#5e81ac'
      shape_list: '#5e81ac'
      shape_literal: '#4c7a8a'
      shape_matching_brackets: { attr: u }
      shape_nothing: '#5e81ac'
      shape_operator: '#4c7a8a'
      shape_or: '#5e81ac'
      shape_pipe: '#5e81ac'
      shape_range: '#5e81ac'
      shape_record: '#5e81ac'
      shape_redirection: '#5e81ac'
      shape_signature: '#5e81ac'
      shape_string: '#2e3440'
      shape_string_interpolation: '#5e81ac'
      shape_table: '#5e81ac'
      shape_variable: '#4c7a8a'
    }
}

export def fallout-dark-explore-config [] {
    {
      help_banner: true
      exit_esc: true
      command_bar_text: '#88c0d0'
      status_bar_background: { fg: '#2e3440' bg: '#88c0d0' }
      highlight: { bg: '#616e82' fg: '#88c0d0' }
      status: {}
      try: {}
      table: { split_line: '#616e82' cursor: true line_index: true line_shift: true line_head_top: true line_head_bottom: true show_head: true show_index: true }
      config: { cursor_color: { bg: '#616e82' fg: '#88c0d0' } }
    }
}

export def fallout-light-explore-config [] {
    {
      help_banner: true
      exit_esc: true
      command_bar_text: '#5e81ac'
      status_bar_background: { fg: '#eceff4' bg: '#5e81ac' }
      highlight: { bg: '#5e81ac' fg: '#5e81ac' }
      status: {}
      try: {}
      table: { split_line: '#5e81ac' cursor: true line_index: true line_shift: true line_head_top: true line_head_bottom: true show_head: true show_index: true }
      config: { cursor_color: { bg: '#5e81ac' fg: '#5e81ac' } }
    }
}

export def fallout-color-config [variant: string = "dark"] {
  if $variant == "light" { fallout-light-color-config } else { fallout-dark-color-config }
}

export def fallout-explore-config [variant: string = "dark"] {
  if $variant == "light" { fallout-light-explore-config } else { fallout-dark-explore-config }
}
