# Cross-platform baseline packages (macOS + Linux)

brew "act"
brew "bat"
brew "ccache"
brew "cloudflared"
brew "cmake"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "doctl"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git-filter-repo"
brew "gitleaks"
brew "gnupg"
brew "jq"
brew "lazygit"
brew "mise"
brew "neovim"
brew "rclone"
brew "ripgrep"
brew "stow"
brew "tree"
brew "watchexec"
brew "wget"
brew "zoxide"
