#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Kitty
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# Neo Vim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# nushell
rm $nu.env-path
rm $nu.config-path
ln -s $DOTFILES/nu/env.nu $nu.env-path
ln -s $DOTFILES/nu/config.nu $nu.config-path

# Starship
rm -rf $HOME/.config/starship.toml
ln -s $DOTFILES/starship.toml $HOME/.config/

# Aerospace
rm -rf $HOME/.aerospace.toml
ln -s $DOTFLES/.aerospace.toml $HOME/
