-- Generated by scripts/theme.ts from themes/nord/.
return {
  normal = { a = { fg = "#2e3440", bg = "#88c0d0", gui = "bold" }, b = { fg = "#eceff4", bg = "#434c5e" }, c = { fg = "#eceff4", bg = "#3b4252" } },
  insert = { a = { fg = "#2e3440", bg = "#8fbcbb", gui = "bold" }, b = { fg = "#eceff4", bg = "#434c5e" }, c = { fg = "#eceff4", bg = "#3b4252" } },
  visual = { a = { fg = "#2e3440", bg = "#b48ead", gui = "bold" }, b = { fg = "#eceff4", bg = "#434c5e" }, c = { fg = "#eceff4", bg = "#3b4252" } },
  replace = { a = { fg = "#2e3440", bg = "#bf616a", gui = "bold" }, b = { fg = "#eceff4", bg = "#434c5e" }, c = { fg = "#eceff4", bg = "#3b4252" } },
  command = { a = { fg = "#2e3440", bg = "#ebcb8b", gui = "bold" }, b = { fg = "#eceff4", bg = "#434c5e" }, c = { fg = "#eceff4", bg = "#3b4252" } },
  inactive = { a = { fg = "#4c566a", bg = "#2e3440" }, b = { fg = "#4c566a", bg = "#2e3440" }, c = { fg = "#4c566a", bg = "#2e3440" } },
}
