palette = 'fallout_hud'
add_newline = false

format = "$directory$git_branch$git_status$fill$cmd_duration$line_break$character"
right_format = "$status"

[palettes.fallout_hud]
bg = '#0b120c'
panel = '#101a12'
green = '#9cff57'
greenSoft = '#73c95a'
greenDim = '#4a7a3f'
greenPale = '#c7ffb0'
gray = '#4f6651'
alert = '#7fbf5a'

[directory]
style = 'bold fg:green'
read_only_style = 'fg:greenDim'
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '~'

[git_branch]
symbol = 'BR:'
style = 'fg:greenSoft'
format = '[[ $symbol$branch ]($style)]($style) '

[git_status]
style = 'fg:greenDim'
format = '[[ $all_status$ahead_behind ]($style)]($style) '
conflicted = 'CNF:${count}'
ahead = 'UP:${count}'
behind = 'DN:${count}'
diverged = 'DV:${ahead_count}/${behind_count}'
untracked = 'UN:${count}'
stashed = 'ST:${count}'
modified = 'MD:${count}'
staged = 'SG:${count}'
renamed = 'RN:${count}'
deleted = 'DL:${count}'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
style = 'fg:greenDim'
format = '[T+${duration}]($style)'

[status]
disabled = false
style = 'bold fg:green'
success_style = 'fg:greenDim'
format = '[EXIT:$status]($style) '
symbol = ''
success_symbol = ''
map_symbol = false

[character]
success_symbol = '[>](bold fg:green) '
error_symbol = '[>](bold fg:greenSoft) '
vimcmd_symbol = '[<](bold fg:greenDim) '

[aws]
format = ''
style = ''
symbol = ''
