#!/usr/bin/env bun

import { mkdir, readFile, readdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";

type Colors = Record<string, string>;

type Theme = {
  id: string;
  family: string;
  variant: "dark" | "light";
  appearance: "dark" | "light";
  colors: Colors;
  ansi: Colors;
};

type Profile = {
  name: string;
  activeTheme: string;
  activeVariant: "dark" | "light";
};

const root = path.resolve(import.meta.dir, "..");

function generatedHeader(family: string): string {
  return `Generated by scripts/theme.ts from themes/${family}/.`;
}

const ansiOrder = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "brightBlack",
  "brightRed",
  "brightGreen",
  "brightYellow",
  "brightBlue",
  "brightMagenta",
  "brightCyan",
  "brightWhite",
] as const;

const requiredColorKeys = [
  "background",
  "deepBackground",
  "surface",
  "surfaceAlt",
  "infoSurface",
  "userSurface",
  "toolPendingSurface",
  "toolSuccessSurface",
  "toolErrorSurface",
  "foreground",
  "muted",
  "dim",
  "accent",
  "accentSoft",
  "cyan",
  "blue",
  "info",
  "purple",
  "amber",
  "error",
  "diffAdded",
  "diffRemoved",
  "string",
] as const;

function hex(value: string): string {
  if (!/^#[0-9a-f]{6}$/i.test(value)) {
    throw new Error(`Invalid color: ${value}`);
  }
  return value.toLowerCase();
}

function rgb(value: string): string {
  const normalized = hex(value).slice(1);
  return [0, 2, 4].map((offset) => Number.parseInt(normalized.slice(offset, offset + 2), 16)).join(" ");
}

function nuString(value: string): string {
  return `'${hex(value)}'`;
}

async function loadThemes(): Promise<Theme[]> {
  const themesRoot = path.join(root, "themes");
  const directories = await readdir(themesRoot, { withFileTypes: true });
  const themes: Theme[] = [];

  for (const directory of directories.filter((entry) => entry.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
    for (const variant of ["dark", "light"] as const) {
      const file = path.join(themesRoot, directory.name, `${variant}.json`);
      try {
        const theme = JSON.parse(await readFile(file, "utf8")) as Theme;
        if (theme.variant !== variant) throw new Error(`${file}: variant does not match filename`);
        for (const value of Object.values(theme.colors)) hex(value);
        for (const value of Object.values(theme.ansi)) hex(value);
        for (const name of ansiOrder) {
          if (!theme.ansi[name]) throw new Error(`${file}: missing ANSI color ${name}`);
        }
        themes.push(theme);
      } catch (error) {
        if ((error as NodeJS.ErrnoException)?.code === "ENOENT") continue;
        throw error;
      }
    }
  }

  if (themes.length === 0) throw new Error("No theme palettes found under themes/*/");
  return themes;
}

async function loadProfile(): Promise<Profile> {
  return JSON.parse(await readFile(path.join(root, "themes", "profile.json"), "utf8")) as Profile;
}

async function writeGenerated(relativePath: string, content: string): Promise<void> {
  const target = path.join(root, relativePath);
  await mkdir(path.dirname(target), { recursive: true });
  const temporary = `${target}.tmp-${process.pid}`;
  await writeFile(temporary, content.endsWith("\n") ? content : `${content}\n`, "utf8");
  await rename(temporary, target);
}

function renderPi(theme: Theme, name = theme.id): string {
  const c = theme.colors;
  const vars = {
    bg: c.background,
    panel: c.surface,
    green: c.accent,
    greenSoft: c.accentSoft,
    greenDim: c.dim,
    greenPale: c.foreground,
    amber: c.amber,
    red: c.error,
    blue: c.blue,
    purple: c.purple,
    cyan: c.cyan,
    gray: c.muted,
  };

  const colors = {
    accent: "green",
    border: "greenDim",
    borderAccent: "green",
    borderMuted: "gray",
    success: "green",
    error: "red",
    warning: "amber",
    muted: "greenDim",
    dim: "gray",
    text: "",
    thinkingText: "greenSoft",
    selectedBg: c.surfaceAlt,
    userMessageBg: c.userSurface,
    userMessageText: "greenPale",
    customMessageBg: c.userSurface,
    customMessageText: "greenPale",
    customMessageLabel: "green",
    toolPendingBg: c.toolPendingSurface,
    toolSuccessBg: c.toolSuccessSurface,
    toolErrorBg: c.toolErrorSurface,
    toolTitle: "green",
    toolOutput: "greenPale",
    mdHeading: "greenPale",
    mdLink: "cyan",
    mdLinkUrl: "greenDim",
    mdCode: "cyan",
    mdCodeBlock: "greenPale",
    mdCodeBlockBorder: "greenDim",
    mdQuote: "greenSoft",
    mdQuoteBorder: "greenDim",
    mdHr: "greenDim",
    mdListBullet: "green",
    toolDiffAdded: c.diffAdded,
    toolDiffRemoved: c.diffRemoved,
    toolDiffContext: "greenDim",
    syntaxComment: "greenDim",
    syntaxKeyword: "green",
    syntaxFunction: "blue",
    syntaxVariable: "greenPale",
    syntaxString: c.string,
    syntaxNumber: "amber",
    syntaxType: "cyan",
    syntaxOperator: "green",
    syntaxPunctuation: "greenSoft",
    thinkingOff: "greenDim",
    thinkingMinimal: "greenSoft",
    thinkingLow: "green",
    thinkingMedium: "cyan",
    thinkingHigh: "purple",
    thinkingXhigh: "red",
    bashMode: "amber",
  };

  return `${JSON.stringify({
    $schema: "https://raw.githubusercontent.com/badlogic/pi-mono/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
    name,
    vars,
    colors,
    export: {
      pageBg: c.deepBackground,
      cardBg: c.surface,
      infoBg: c.infoSurface,
    },
  }, null, 2)}\n`;
}

function renderKitty(theme: Theme, role: string): string {
  const c = theme.colors;
  const a = theme.ansi;
  const lines = [
    "# vim:ft=kitty",
    `# ${generatedHeader(theme.family)}`,
    `# ${role} variant: ${theme.id}`,
    "",
    "foreground                      " + c.foreground,
    "background                      " + c.background,
    "selection_foreground            " + c.foreground,
    "selection_background            " + c.surfaceAlt,
    "",
    "cursor                          " + c.accent,
    "cursor_text_color               " + c.background,
    "",
    "url_color                       " + c.cyan,
    "",
    "active_tab_foreground           " + c.foreground,
    "active_tab_background           " + c.surface,
    "inactive_tab_foreground         " + c.muted,
    "inactive_tab_background         " + c.background,
    "",
    ...ansiOrder.map((name, index) => `color${index.toString().padEnd(3, " ")} ${a[name]}`),
  ];
  return `${lines.join("\n")}\n`;
}

function renderStarship(theme: Theme): string {
  const c = theme.colors;
  return `# ${generatedHeader(theme.family)}
palette = 'fallout_terminal'
add_newline = false

format = "$directory$git_branch$git_status$fill$cmd_duration$line_break$character"
right_format = "$status"

[palettes.fallout_terminal]
bg = '${c.background}'
panel = '${c.surface}'
green = '${c.accent}'
greenSoft = '${c.accentSoft}'
greenDim = '${c.dim}'
greenPale = '${c.foreground}'
gray = '${c.muted}'
cyan = '${c.cyan}'
blue = '${c.blue}'
amber = '${c.amber}'
red = '${c.error}'

[directory]
style = 'bold fg:green'
read_only_style = 'fg:greenDim'
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 3
truncation_symbol = '…/'
home_symbol = '~'

[git_branch]
symbol = 'BR:'
style = 'fg:greenSoft'
format = '[[ $symbol$branch ]($style)]($style) '

[git_status]
style = 'fg:greenDim'
format = '[[ $all_status$ahead_behind ]($style)]($style) '
conflicted = 'CNF:\${count}'
ahead = 'UP:\${count}'
behind = 'DN:\${count}'
diverged = 'DV:\${ahead_count}/\${behind_count}'
untracked = 'UN:\${count}'
stashed = 'ST:\${count}'
modified = 'MD:\${count}'
staged = 'SG:\${count}'
renamed = 'RN:\${count}'
deleted = 'DL:\${count}'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
style = 'fg:greenDim'
format = '[T+\${duration}]($style)'

[status]
disabled = false
style = 'bold fg:red'
success_style = 'fg:greenDim'
format = '[EXIT:$status]($style) '
symbol = ''
success_symbol = ''
map_symbol = false

[character]
success_symbol = '[>](bold fg:green) '
error_symbol = '[>](bold fg:red) '
vimcmd_symbol = '[<](bold fg:greenDim) '

[aws]
format = ''
style = ''
symbol = ''
`;
}

type ZellijFields = Record<string, string>;

function zellijBlock(name: string, fields: ZellijFields): string {
  return `        ${name} {\n${Object.entries(fields)
    .map(([key, value]) => `            ${key} ${rgb(value)}`)
    .join("\n")}\n        }`;
}

function renderZellij(theme: Theme, name = theme.id): string {
  const c = theme.colors;
  const fields = (base: string, background: string, emphasis0: string, emphasis1: string, emphasis2: string, emphasis3: string) => ({
    base,
    background,
    emphasis_0: emphasis0,
    emphasis_1: emphasis1,
    emphasis_2: emphasis2,
    emphasis_3: emphasis3,
  });

  const blocks = [
    zellijBlock("text_unselected", fields(c.foreground, c.background, c.amber, c.cyan, c.accent, c.purple)),
    zellijBlock("text_selected", fields(c.foreground, c.surfaceAlt, c.amber, c.cyan, c.accent, c.purple)),
    zellijBlock("ribbon_selected", fields(c.background, c.accent, c.error, c.amber, c.purple, c.info)),
    zellijBlock("ribbon_unselected", fields(c.foreground, c.background, c.error, c.dim, c.blue, c.purple)),
    zellijBlock("table_title", fields(c.accent, c.background, c.amber, c.cyan, c.accentSoft, c.purple)),
    zellijBlock("table_cell_selected", fields(c.foreground, c.surfaceAlt, c.amber, c.cyan, c.accent, c.purple)),
    zellijBlock("table_cell_unselected", fields(c.foreground, c.background, c.amber, c.cyan, c.accent, c.purple)),
    zellijBlock("list_selected", fields(c.foreground, c.surfaceAlt, c.amber, c.cyan, c.accent, c.purple)),
    zellijBlock("list_unselected", fields(c.foreground, c.background, c.amber, c.cyan, c.accent, c.purple)),
    zellijBlock("frame_selected", fields(c.accent, c.background, c.amber, c.accentSoft, c.purple, c.background)),
    zellijBlock("frame_highlight", fields(c.amber, c.background, c.accent, c.background, c.amber, c.amber)),
    zellijBlock("exit_code_success", fields(c.accent, c.background, c.accentSoft, c.foreground, c.cyan, c.blue)),
    zellijBlock("exit_code_error", fields(c.error, c.background, c.amber, c.background, c.background, c.background)),
    `        multiplayer_user_colors {\n${[
      c.accent,
      c.blue,
      c.accentSoft,
      c.amber,
      c.cyan,
      c.muted,
      c.error,
      c.purple,
      c.foreground,
      c.dim,
    ].map((value, index) => `            player_${index + 1} ${rgb(value)}`).join("\n")}\n        }`,
  ];

  return `// ${generatedHeader(theme.family)}\nthemes {\n    ${name} {\n${blocks.join("\n")}\n    }\n}\n`;
}

function renderZellijThemesBlock(profile: Profile, themes: Theme[]): string {
  const { active, dark, light } = activeThemes(profile, themes);
  const entries = [
    { theme: active, name: "fallout-terminal" },
    { theme: dark, name: "fallout-terminal-dark" },
    { theme: light, name: "fallout-terminal-light" },
  ];

  const nodes = entries.map(({ theme, name }) => {
    const rendered = renderZellij(theme, name);
    const start = rendered.indexOf(`    ${name} {`);
    const end = rendered.lastIndexOf("\n}\n");
    if (start < 0 || end < 0) throw new Error(`Unable to extract generated Zellij theme ${name}`);
    return rendered.slice(start, end);
  });

  return `themes {\n${nodes.join("\n")}\n}`;
}

function replaceZellijThemeBlock(config: string, block: string): string {
  const startMarker = "// BEGIN GENERATED THEMES";
  const endMarker = "// END GENERATED THEMES";
  const start = config.indexOf(startMarker);
  const end = config.indexOf(endMarker);
  if (start < 0 || end < start) throw new Error("Zellij config is missing generated theme markers");
  const before = config.slice(0, start);
  const after = config.slice(end + endMarker.length);
  return `${before}${startMarker}\n${block}\n${endMarker}${after}`;
}

function extractZellijThemeBlock(config: string): string {
  const startMarker = "// BEGIN GENERATED THEMES";
  const endMarker = "// END GENERATED THEMES";
  const start = config.indexOf(startMarker);
  const end = config.indexOf(endMarker);
  if (start < 0 || end < start) throw new Error("Zellij config is missing generated theme markers");
  return config.slice(start + startMarker.length, end).trim();
}

function nuRecord(entries: string[]): string {
  return `    {\n${entries.map((entry) => `      ${entry}`).join("\n")}\n    }`;
}

function renderNuColorConfig(theme: Theme): string {
  const c = theme.colors;
  const fg = nuString(c.foreground);
  const accent = nuString(c.accent);
  const soft = nuString(c.accentSoft);
  const dim = nuString(c.dim);
  const bg = nuString(c.background);
  return nuRecord([
    `separator: ${soft}`,
    `leading_trailing_space_bg: { attr: n }`,
    `header: ${accent}`,
    `empty: ${soft}`,
    `bool: ${accent}`,
    `int: ${fg}`,
    `filesize: ${fg}`,
    `duration: ${soft}`,
    `date: ${soft}`,
    `range: ${soft}`,
    `float: ${fg}`,
    `string: ${fg}`,
    `nothing: ${dim}`,
    `binary: ${fg}`,
    `cellpath: ${fg}`,
    `row_index: ${accent}`,
    `record: ${fg}`,
    `list: ${fg}`,
    `block: ${fg}`,
    `hints: ${dim}`,
    `shape_and: ${accent}`,
    `shape_binary: ${accent}`,
    `shape_block: ${accent}`,
    `shape_bool: ${accent}`,
    `shape_custom: ${soft}`,
    `shape_datetime: ${accent}`,
    `shape_directory: ${accent}`,
    `shape_external: ${accent}`,
    `shape_externalarg: ${accent}`,
    `shape_filepath: ${accent}`,
    `shape_flag: ${accent}`,
    `shape_float: ${accent}`,
    `shape_garbage: { fg: ${accent} bg: ${dim} attr: b }`,
    `shape_globpattern: ${accent}`,
    `shape_int: ${accent}`,
    `shape_internalcall: ${accent}`,
    `shape_list: ${accent}`,
    `shape_literal: ${soft}`,
    `shape_matching_brackets: { attr: u }`,
    `shape_nothing: ${accent}`,
    `shape_operator: ${soft}`,
    `shape_or: ${accent}`,
    `shape_pipe: ${accent}`,
    `shape_range: ${accent}`,
    `shape_record: ${accent}`,
    `shape_redirection: ${accent}`,
    `shape_signature: ${accent}`,
    `shape_string: ${fg}`,
    `shape_string_interpolation: ${accent}`,
    `shape_table: ${accent}`,
    `shape_variable: ${soft}`,
  ]);
}

function renderNuExploreConfig(theme: Theme): string {
  const c = theme.colors;
  return nuRecord([
    "help_banner: true",
    "exit_esc: true",
    `command_bar_text: ${nuString(c.accent)}`,
    `status_bar_background: { fg: ${nuString(c.background)} bg: ${nuString(c.accent)} }`,
    `highlight: { bg: ${nuString(c.dim)} fg: ${nuString(c.accent)} }`,
    "status: {}",
    "try: {}",
    `table: { split_line: ${nuString(c.dim)} cursor: true line_index: true line_shift: true line_head_top: true line_head_bottom: true show_head: true show_index: true }`,
    `config: { cursor_color: { bg: ${nuString(c.dim)} fg: ${nuString(c.accent)} } }`,
  ]);
}

function renderNu(themeDark: Theme, themeLight: Theme, activeVariant: "dark" | "light"): string {
  return `# ${generatedHeader(themeDark.family)}

export def fallout-default-variant [] {\n  "${activeVariant}"\n}\n\nexport def fallout-dark-color-config [] {
${renderNuColorConfig(themeDark)}
}

export def fallout-light-color-config [] {
${renderNuColorConfig(themeLight)}
}

export def fallout-dark-explore-config [] {
${renderNuExploreConfig(themeDark)}
}

export def fallout-light-explore-config [] {
${renderNuExploreConfig(themeLight)}
}

export def fallout-color-config [variant: string = "dark"] {
  if $variant == "light" { fallout-light-color-config } else { fallout-dark-color-config }
}

export def fallout-explore-config [variant: string = "dark"] {
  if $variant == "light" { fallout-light-explore-config } else { fallout-dark-explore-config }
}
`;
}

type LuaHighlight = Record<string, string | boolean>;

function renderLuaHighlight(highlight: LuaHighlight): string {
  return `{ ${Object.entries(highlight)
    .map(([key, value]) => `${key} = ${typeof value === "boolean" ? value : `"${value}"`}`)
    .join(", ")} }`;
}

function renderNvimColorscheme(theme: Theme, colorschemeName: string): string {
  const c = theme.colors;
  const groups: Array<[string, LuaHighlight]> = [
    ["Normal", { fg: c.foreground, bg: c.background }],
    ["NormalFloat", { fg: c.foreground, bg: c.surface }],
    ["NormalNC", { fg: c.foreground, bg: c.background }],
    ["Cursor", { fg: c.background, bg: c.accent }],
    ["CursorLine", { bg: c.surface }],
    ["CursorLineNr", { fg: c.accent, bg: c.surface, bold: true }],
    ["LineNr", { fg: c.muted }],
    ["SignColumn", { fg: c.dim, bg: c.background }],
    ["FoldColumn", { fg: c.dim, bg: c.background }],
    ["WinSeparator", { fg: c.dim, bg: c.background }],
    ["StatusLine", { fg: c.foreground, bg: c.surface }],
    ["StatusLineNC", { fg: c.muted, bg: c.background }],
    ["TabLine", { fg: c.muted, bg: c.background }],
    ["TabLineFill", { fg: c.muted, bg: c.background }],
    ["TabLineSel", { fg: c.background, bg: c.accent, bold: true }],
    ["Visual", { bg: c.surfaceAlt }],
    ["Search", { fg: c.background, bg: c.amber }],
    ["IncSearch", { fg: c.background, bg: c.accent }],
    ["Substitute", { fg: c.background, bg: c.amber }],
    ["Pmenu", { fg: c.foreground, bg: c.surface }],
    ["PmenuSel", { fg: c.background, bg: c.accent }],
    ["PmenuSbar", { bg: c.surfaceAlt }],
    ["PmenuThumb", { bg: c.dim }],
    ["Comment", { fg: c.dim, italic: true }],
    ["Constant", { fg: c.amber }],
    ["String", { fg: c.string }],
    ["Character", { fg: c.string }],
    ["Number", { fg: c.amber }],
    ["Boolean", { fg: c.amber }],
    ["Identifier", { fg: c.foreground }],
    ["Function", { fg: c.blue }],
    ["Statement", { fg: c.accent, bold: true }],
    ["Conditional", { fg: c.accent, bold: true }],
    ["Repeat", { fg: c.accent, bold: true }],
    ["Label", { fg: c.cyan }],
    ["Operator", { fg: c.accentSoft }],
    ["Keyword", { fg: c.accent, bold: true }],
    ["Exception", { fg: c.error }],
    ["PreProc", { fg: c.purple }],
    ["Include", { fg: c.purple }],
    ["Define", { fg: c.purple }],
    ["Macro", { fg: c.purple }],
    ["Type", { fg: c.cyan }],
    ["StorageClass", { fg: c.cyan }],
    ["Structure", { fg: c.cyan }],
    ["Typedef", { fg: c.cyan }],
    ["Special", { fg: c.cyan }],
    ["SpecialComment", { fg: c.dim }],
    ["Error", { fg: c.error, bold: true }],
    ["Todo", { fg: c.background, bg: c.amber, bold: true }],
    ["DiagnosticError", { fg: c.error }],
    ["DiagnosticWarn", { fg: c.amber }],
    ["DiagnosticInfo", { fg: c.blue }],
    ["DiagnosticHint", { fg: c.cyan }],
    ["DiffAdd", { fg: c.diffAdded, bg: c.toolSuccessSurface ?? c.surface }],
    ["DiffDelete", { fg: c.diffRemoved, bg: c.toolErrorSurface ?? c.surface }],
    ["DiffChange", { fg: c.amber, bg: c.surface }],
    ["DiffText", { fg: c.background, bg: c.amber }],
    ["GitSignsAdd", { fg: c.diffAdded }],
    ["GitSignsChange", { fg: c.amber }],
    ["GitSignsDelete", { fg: c.diffRemoved }],
    ["TelescopeBorder", { fg: c.dim, bg: c.surface }],
    ["TelescopePromptBorder", { fg: c.accent, bg: c.surface }],
    ["TelescopeSelection", { fg: c.foreground, bg: c.surfaceAlt }],
    ["TelescopeMatching", { fg: c.accent, bold: true }],
    ["WhichKey", { fg: c.accent }],
    ["WhichKeyGroup", { fg: c.cyan }],
    ["IblIndent", { fg: c.dim }],
    ["DashboardHeader", { fg: c.accent }],
    ["DashboardDesc", { fg: c.accent }],
    ["DashboardIcon", { fg: c.accent }],
    ["DashboardKey", { fg: c.accent }],
    ["DashboardFooter", { fg: c.accent }],
    ["TroubleText", { fg: c.foreground }],
    ["TroubleCount", { fg: c.cyan }],
    ["OilDir", { fg: c.blue }],
    ["BlinkCmpMenu", { fg: c.foreground, bg: c.surface }],
    ["BlinkCmpMenuSelection", { fg: c.background, bg: c.accent }],
    ["@comment", { fg: c.dim, italic: true }],
    ["@constant", { fg: c.amber }],
    ["@string", { fg: c.string }],
    ["@number", { fg: c.amber }],
    ["@boolean", { fg: c.amber }],
    ["@variable", { fg: c.foreground }],
    ["@parameter", { fg: c.foreground }],
    ["@function", { fg: c.blue }],
    ["@function.call", { fg: c.blue }],
    ["@keyword", { fg: c.accent, bold: true }],
    ["@keyword.function", { fg: c.accent, bold: true }],
    ["@type", { fg: c.cyan }],
    ["@type.builtin", { fg: c.cyan }],
    ["@operator", { fg: c.accentSoft }],
    ["@property", { fg: c.cyan }],
    ["@tag", { fg: c.accent }],
    ["@tag.attribute", { fg: c.cyan }],
  ];

  const terminal = ansiOrder.map((name, index) => `vim.g.terminal_color_${index} = "${theme.ansi[name]}"`);
  return `-- ${generatedHeader(theme.family)}
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "${theme.appearance}"
vim.g.colors_name = "${colorschemeName}"

local set = vim.api.nvim_set_hl

${groups.map(([name, highlight]) => `set(0, "${name}", ${renderLuaHighlight(highlight)})`).join("\n")}

${terminal.join("\n")}
`;
}

function renderLualineTheme(theme: Theme): string {
  const c = theme.colors;
  return `-- ${generatedHeader(theme.family)}
return {
  normal = { a = { fg = "${c.background}", bg = "${c.accent}", gui = "bold" }, b = { fg = "${c.foreground}", bg = "${c.surfaceAlt}" }, c = { fg = "${c.foreground}", bg = "${c.surface}" } },
  insert = { a = { fg = "${c.background}", bg = "${c.cyan}", gui = "bold" }, b = { fg = "${c.foreground}", bg = "${c.surfaceAlt}" }, c = { fg = "${c.foreground}", bg = "${c.surface}" } },
  visual = { a = { fg = "${c.background}", bg = "${c.purple}", gui = "bold" }, b = { fg = "${c.foreground}", bg = "${c.surfaceAlt}" }, c = { fg = "${c.foreground}", bg = "${c.surface}" } },
  replace = { a = { fg = "${c.background}", bg = "${c.error}", gui = "bold" }, b = { fg = "${c.foreground}", bg = "${c.surfaceAlt}" }, c = { fg = "${c.foreground}", bg = "${c.surface}" } },
  command = { a = { fg = "${c.background}", bg = "${c.amber}", gui = "bold" }, b = { fg = "${c.foreground}", bg = "${c.surfaceAlt}" }, c = { fg = "${c.foreground}", bg = "${c.surface}" } },
  inactive = { a = { fg = "${c.muted}", bg = "${c.background}" }, b = { fg = "${c.muted}", bg = "${c.background}" }, c = { fg = "${c.muted}", bg = "${c.background}" } },
}
`;
}

function renderNvimPalette(themeDark: Theme, themeLight: Theme, activeVariant: "dark" | "light"): string {
  const render = (theme: Theme) => {
    const c = theme.colors;
    return `  ${theme.variant} = {\n${Object.entries({
      bg: c.background,
      deepBackground: c.deepBackground,
      surface: c.surface,
      surfaceAlt: c.surfaceAlt,
      foreground: c.foreground,
      muted: c.muted,
      dim: c.dim,
      accent: c.accent,
      accentSoft: c.accentSoft,
      cyan: c.cyan,
      blue: c.blue,
      info: c.info,
      purple: c.purple,
      amber: c.amber,
      error: c.error,
      diffAdded: c.diffAdded,
      diffRemoved: c.diffRemoved,
      string: c.string,
    }).map(([key, value]) => `    ${key} = "${value}"`).join(",\n")}\n  }`;
  };

  return `-- ${generatedHeader(themeDark.family)}\nreturn {\n  active = "${activeVariant}",\n${render(themeDark)},\n${render(themeLight)},\n}\n`;
}

function validateInputs(profile: Profile, themes: Theme[]): void {
  if (!profile.activeTheme) throw new Error("themes/profile.json is missing activeTheme");
  if (profile.activeVariant !== "dark" && profile.activeVariant !== "light") {
    throw new Error(`Invalid activeVariant: ${String(profile.activeVariant)}`);
  }

  const ids = new Set<string>();
  for (const theme of themes) {
    if (!theme.id || !theme.family) throw new Error("Every palette needs an id and family");
    if (ids.has(theme.id)) throw new Error(`Duplicate theme id: ${theme.id}`);
    ids.add(theme.id);
    if (theme.id !== `${theme.family}-${theme.variant}`) {
      throw new Error(`${theme.id}: expected id ${theme.family}-${theme.variant}`);
    }
    if (theme.appearance !== theme.variant) throw new Error(`${theme.id}: appearance must match variant`);
    for (const key of requiredColorKeys) {
      if (!theme.colors[key]) throw new Error(`${theme.id}: missing color ${key}`);
    }
  }

  const families = new Set(themes.map((theme) => theme.family));
  if (!families.has(profile.activeTheme)) {
    throw new Error(`Unknown active theme family: ${profile.activeTheme}`);
  }
  for (const variant of ["dark", "light"] as const) {
    if (!themes.some((theme) => theme.family === profile.activeTheme && theme.variant === variant)) {
      throw new Error(`${profile.activeTheme}: missing ${variant} variant`);
    }
  }
}

function findTheme(themes: Theme[], family: string, variant: "dark" | "light"): Theme {
  const theme = themes.find((candidate) => candidate.family === family && candidate.variant === variant);
  if (!theme) throw new Error(`No ${variant} variant exists for theme ${family}`);
  return theme;
}

function activeThemes(profile: Profile, themes: Theme[]): { active: Theme; dark: Theme; light: Theme } {
  const dark = findTheme(themes, profile.activeTheme, "dark");
  const light = findTheme(themes, profile.activeTheme, "light");
  return { active: profile.activeVariant === "light" ? light : dark, dark, light };
}

type GeneratedFile = {
  path: string;
  content: string;
};

function renderOutputs(profile: Profile, themes: Theme[]): GeneratedFile[] {
  const { active, dark, light } = activeThemes(profile, themes);
  const outputs: GeneratedFile[] = [
    { path: "kitty/.config/kitty/dark-theme.auto.conf", content: renderKitty(dark, "dark") },
    { path: "kitty/.config/kitty/light-theme.auto.conf", content: renderKitty(light, "light") },
    { path: "kitty/.config/kitty/no-preference-theme.auto.conf", content: renderKitty(dark, "no-preference") },
    { path: "pi/.pi/agent/themes/fallout-terminal.json", content: renderPi(active, "fallout-terminal") },
    { path: "starship/.config/starship.toml", content: renderStarship(active) },
    { path: "starship/.config/starship-light.toml", content: renderStarship(light) },
    { path: "zellij/.config/zellij/themes/fallout-terminal.kdl", content: renderZellij(active, "fallout-terminal") },
    { path: "nu/.config/nushell/theme.nu", content: renderNu(dark, light, profile.activeVariant) },
    { path: "nvim/.config/nvim/colors/fallout-terminal.lua", content: renderNvimColorscheme(active, "fallout-terminal") },
    { path: "nvim/.config/nvim/lua/christian/lualine_theme.lua", content: renderLualineTheme(active) },
    { path: "nvim/.config/nvim/lua/christian/theme_palette.lua", content: renderNvimPalette(dark, light, profile.activeVariant) },
  ];

  for (const theme of themes) {
    outputs.push(
      { path: `pi/.pi/agent/themes/${theme.id}.json`, content: renderPi(theme) },
      { path: `zellij/.config/zellij/themes/${theme.id}.kdl`, content: renderZellij(theme) },
      { path: `nvim/.config/nvim/colors/${theme.id}.lua`, content: renderNvimColorscheme(theme, theme.id) },
    );
  }

  return outputs;
}

async function generate(): Promise<void> {
  const profile = await loadProfile();
  const themes = await loadThemes();
  const { active } = activeThemes(profile, themes);
  validateInputs(profile, themes);

  for (const output of renderOutputs(profile, themes)) {
    await writeGenerated(output.path, output.content);
  }

  const zellijConfigPath = path.join(root, "zellij", ".config", "zellij", "config.kdl");
  const zellijConfig = await readFile(zellijConfigPath, "utf8");
  await writeGenerated(
    "zellij/.config/zellij/config.kdl",
    replaceZellijThemeBlock(zellijConfig, renderZellijThemesBlock(profile, themes)),
  );

  console.log(`Generated ${active.family} (${active.variant}) themes.`);
}

async function check(): Promise<void> {
  const profile = await loadProfile();
  const themes = await loadThemes();
  const { active } = activeThemes(profile, themes);
  validateInputs(profile, themes);

  const outputs = renderOutputs(profile, themes);
  const drift: string[] = [];
  for (const output of outputs) {
    const target = path.join(root, output.path);
    let actual: string;
    try {
      actual = await readFile(target, "utf8");
    } catch {
      drift.push(`${output.path} (missing)`);
      continue;
    }
    if (actual !== output.content) drift.push(output.path);
  }
  const zellijConfigPath = path.join(root, "zellij", ".config", "zellij", "config.kdl");
  const zellijConfig = await readFile(zellijConfigPath, "utf8");
  const expectedZellijBlock = renderZellijThemesBlock(profile, themes);
  const actualZellijBlock = extractZellijThemeBlock(zellijConfig);
  if (actualZellijBlock !== expectedZellijBlock) drift.push("zellij/.config/zellij/config.kdl (generated themes)");

  if (drift.length > 0) {
    throw new Error(`Generated theme drift detected:\n${drift.map((item) => `- ${item}`).join("\n")}\nRun: bun scripts/theme.ts generate`);
  }
  console.log(`Theme check passed (active: ${active.family} ${active.variant}; ${outputs.length + 1} generated files).`);
}

function printCurrent(profile: Profile, themes: Theme[]): void {
  const { active } = activeThemes(profile, themes);
  console.log(`${active.family} ${active.variant} (${active.id})`);
}

function printList(profile: Profile, themes: Theme[]): void {
  const families = [...new Set(themes.map((theme) => theme.family))].sort();
  for (const family of families) {
    const variants = themes
      .filter((theme) => theme.family === family)
      .map((theme) => theme.variant)
      .sort()
      .join(", ");
    const marker = family === profile.activeTheme ? " *" : "";
    console.log(`${family}: ${variants}${marker}`);
  }
}

async function setTheme(args: string[]): Promise<void> {
  if (args.length < 1 || args.length > 2) {
    throw new Error("Usage: theme <dark|light|toggle|family> [dark|light]");
  }

  const profile = await loadProfile();
  const themes = await loadThemes();
  validateInputs(profile, themes);

  const variants = new Set(["dark", "light"]);
  const isToggle = args[0] === "toggle";
  const requestedFamily = isToggle || variants.has(args[0]) ? profile.activeTheme : args[0];
  const requestedVariant = isToggle
    ? (profile.activeVariant === "dark" ? "light" : "dark")
    : (variants.has(args[0]) ? args[0] : args[1]) as "dark" | "light" | undefined;
  if (requestedVariant && !variants.has(requestedVariant)) {
    throw new Error(`Unknown variant: ${requestedVariant}`);
  }
  if (!themes.some((theme) => theme.family === requestedFamily)) {
    throw new Error(`Unknown theme family: ${requestedFamily}. Run: theme list`);
  }

  const variant = requestedVariant ?? (themes.some((theme) => theme.family === requestedFamily && theme.variant === profile.activeVariant)
    ? profile.activeVariant
    : "dark");
  findTheme(themes, requestedFamily, variant);

  await writeGenerated("themes/profile.json", `${JSON.stringify({
    name: profile.name,
    activeTheme: requestedFamily,
    activeVariant: variant,
  }, null, 2)}\n`);
  await generate();

  if (process.env.ZELLIJ) {
    const action = variant === "light" ? "set-light-theme" : "set-dark-theme";
    const result = Bun.spawnSync(["zellij", "action", action], { stdout: "pipe", stderr: "pipe" });
    if (result.exitCode === 0) {
      console.log(`Applied ${variant} theme to the current Zellij session.`);
    } else {
      const message = new TextDecoder().decode(result.stderr).trim();
      console.warn(`Generated the theme, but could not update the current Zellij session${message ? `: ${message}` : "."}`);
    }
  }
}

const command = process.argv[2] ?? "check";
const args = process.argv.slice(3);
const profile = command === "list" || command === "current" ? await loadProfile() : null;
const themes = command === "list" || command === "current" ? await loadThemes() : null;

if (command === "generate") {
  await generate();
} else if (command === "check") {
  await check();
} else if (command === "current") {
  if (!profile || !themes) throw new Error("Unable to load theme state");
  printCurrent(profile, themes);
} else if (command === "list") {
  if (!profile || !themes) throw new Error("Unable to load theme state");
  printList(profile, themes);
} else if (command === "set") {
  await setTheme(args);
} else {
  console.error("Usage: bun scripts/theme.ts [current|list|set <dark|light|toggle|family> [dark|light]|generate|check]");
  process.exit(1);
}
