-- Generated by scripts/theme.ts from themes/fallout-terminal/.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "fallout-terminal-dark"

local set = vim.api.nvim_set_hl

set(0, "Normal", { fg = "#c7ffb0", bg = "#0b120c" })
set(0, "NormalFloat", { fg = "#c7ffb0", bg = "#101a12" })
set(0, "NormalNC", { fg = "#c7ffb0", bg = "#0b120c" })
set(0, "Cursor", { fg = "#0b120c", bg = "#9cff57" })
set(0, "CursorLine", { bg = "#101a12" })
set(0, "CursorLineNr", { fg = "#9cff57", bg = "#101a12", bold = true })
set(0, "LineNr", { fg = "#4f6651" })
set(0, "SignColumn", { fg = "#4a7a3f", bg = "#0b120c" })
set(0, "FoldColumn", { fg = "#4a7a3f", bg = "#0b120c" })
set(0, "WinSeparator", { fg = "#4a7a3f", bg = "#0b120c" })
set(0, "StatusLine", { fg = "#c7ffb0", bg = "#101a12" })
set(0, "StatusLineNC", { fg = "#4f6651", bg = "#0b120c" })
set(0, "TabLine", { fg = "#4f6651", bg = "#0b120c" })
set(0, "TabLineFill", { fg = "#4f6651", bg = "#0b120c" })
set(0, "TabLineSel", { fg = "#0b120c", bg = "#9cff57", bold = true })
set(0, "Visual", { bg = "#162018" })
set(0, "Search", { fg = "#0b120c", bg = "#d6c96b" })
set(0, "IncSearch", { fg = "#0b120c", bg = "#9cff57" })
set(0, "Substitute", { fg = "#0b120c", bg = "#d6c96b" })
set(0, "Pmenu", { fg = "#c7ffb0", bg = "#101a12" })
set(0, "PmenuSel", { fg = "#0b120c", bg = "#9cff57" })
set(0, "PmenuSbar", { bg = "#162018" })
set(0, "PmenuThumb", { bg = "#4a7a3f" })
set(0, "Comment", { fg = "#4a7a3f", italic = true })
set(0, "Constant", { fg = "#d6c96b" })
set(0, "String", { fg = "#a7ff7d" })
set(0, "Character", { fg = "#a7ff7d" })
set(0, "Number", { fg = "#d6c96b" })
set(0, "Boolean", { fg = "#d6c96b" })
set(0, "Identifier", { fg = "#c7ffb0" })
set(0, "Function", { fg = "#7fd7ff" })
set(0, "Statement", { fg = "#9cff57", bold = true })
set(0, "Conditional", { fg = "#9cff57", bold = true })
set(0, "Repeat", { fg = "#9cff57", bold = true })
set(0, "Label", { fg = "#87ffd9" })
set(0, "Operator", { fg = "#73c95a" })
set(0, "Keyword", { fg = "#9cff57", bold = true })
set(0, "Exception", { fg = "#ff6b6b" })
set(0, "PreProc", { fg = "#c48dff" })
set(0, "Include", { fg = "#c48dff" })
set(0, "Define", { fg = "#c48dff" })
set(0, "Macro", { fg = "#c48dff" })
set(0, "Type", { fg = "#87ffd9" })
set(0, "StorageClass", { fg = "#87ffd9" })
set(0, "Structure", { fg = "#87ffd9" })
set(0, "Typedef", { fg = "#87ffd9" })
set(0, "Special", { fg = "#87ffd9" })
set(0, "SpecialComment", { fg = "#4a7a3f" })
set(0, "Error", { fg = "#ff6b6b", bold = true })
set(0, "Todo", { fg = "#0b120c", bg = "#d6c96b", bold = true })
set(0, "DiagnosticError", { fg = "#ff6b6b" })
set(0, "DiagnosticWarn", { fg = "#d6c96b" })
set(0, "DiagnosticInfo", { fg = "#7fd7ff" })
set(0, "DiagnosticHint", { fg = "#87ffd9" })
set(0, "DiffAdd", { fg = "#5fff87", bg = "#102014" })
set(0, "DiffDelete", { fg = "#ff8787", bg = "#201110" })
set(0, "DiffChange", { fg = "#d6c96b", bg = "#101a12" })
set(0, "DiffText", { fg = "#0b120c", bg = "#d6c96b" })
set(0, "GitSignsAdd", { fg = "#5fff87" })
set(0, "GitSignsChange", { fg = "#d6c96b" })
set(0, "GitSignsDelete", { fg = "#ff8787" })
set(0, "TelescopeBorder", { fg = "#4a7a3f", bg = "#101a12" })
set(0, "TelescopePromptBorder", { fg = "#9cff57", bg = "#101a12" })
set(0, "TelescopeSelection", { fg = "#c7ffb0", bg = "#162018" })
set(0, "TelescopeMatching", { fg = "#9cff57", bold = true })
set(0, "WhichKey", { fg = "#9cff57" })
set(0, "WhichKeyGroup", { fg = "#87ffd9" })
set(0, "IblIndent", { fg = "#4a7a3f" })
set(0, "DashboardHeader", { fg = "#9cff57" })
set(0, "DashboardDesc", { fg = "#9cff57" })
set(0, "DashboardIcon", { fg = "#9cff57" })
set(0, "DashboardKey", { fg = "#9cff57" })
set(0, "DashboardFooter", { fg = "#9cff57" })
set(0, "TroubleText", { fg = "#c7ffb0" })
set(0, "TroubleCount", { fg = "#87ffd9" })
set(0, "OilDir", { fg = "#7fd7ff" })
set(0, "BlinkCmpMenu", { fg = "#c7ffb0", bg = "#101a12" })
set(0, "BlinkCmpMenuSelection", { fg = "#0b120c", bg = "#9cff57" })
set(0, "@comment", { fg = "#4a7a3f", italic = true })
set(0, "@constant", { fg = "#d6c96b" })
set(0, "@string", { fg = "#a7ff7d" })
set(0, "@number", { fg = "#d6c96b" })
set(0, "@boolean", { fg = "#d6c96b" })
set(0, "@variable", { fg = "#c7ffb0" })
set(0, "@parameter", { fg = "#c7ffb0" })
set(0, "@function", { fg = "#7fd7ff" })
set(0, "@function.call", { fg = "#7fd7ff" })
set(0, "@keyword", { fg = "#9cff57", bold = true })
set(0, "@keyword.function", { fg = "#9cff57", bold = true })
set(0, "@type", { fg = "#87ffd9" })
set(0, "@type.builtin", { fg = "#87ffd9" })
set(0, "@operator", { fg = "#73c95a" })
set(0, "@property", { fg = "#87ffd9" })
set(0, "@tag", { fg = "#9cff57" })
set(0, "@tag.attribute", { fg = "#87ffd9" })

vim.g.terminal_color_0 = "#0b120c"
vim.g.terminal_color_1 = "#ff6b6b"
vim.g.terminal_color_2 = "#73c95a"
vim.g.terminal_color_3 = "#d6c96b"
vim.g.terminal_color_4 = "#7fd7ff"
vim.g.terminal_color_5 = "#c48dff"
vim.g.terminal_color_6 = "#87ffd9"
vim.g.terminal_color_7 = "#c7ffb0"
vim.g.terminal_color_8 = "#4f6651"
vim.g.terminal_color_9 = "#ff8787"
vim.g.terminal_color_10 = "#9cff57"
vim.g.terminal_color_11 = "#e8dd8a"
vim.g.terminal_color_12 = "#a6e7ff"
vim.g.terminal_color_13 = "#ddb7ff"
vim.g.terminal_color_14 = "#b0ffe8"
vim.g.terminal_color_15 = "#ecffe0"
