-- Generated by scripts/theme.ts from themes/fallout-terminal/.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "light"
vim.g.colors_name = "fallout-terminal-light"

local set = vim.api.nvim_set_hl

set(0, "Normal", { fg = "#18301d", bg = "#f0f5e9" })
set(0, "NormalFloat", { fg = "#18301d", bg = "#e5efdc" })
set(0, "NormalNC", { fg = "#18301d", bg = "#f0f5e9" })
set(0, "Cursor", { fg = "#f0f5e9", bg = "#2f7d32" })
set(0, "CursorLine", { bg = "#e5efdc" })
set(0, "CursorLineNr", { fg = "#2f7d32", bg = "#e5efdc", bold = true })
set(0, "LineNr", { fg = "#55705a" })
set(0, "SignColumn", { fg = "#587b45", bg = "#f0f5e9" })
set(0, "FoldColumn", { fg = "#587b45", bg = "#f0f5e9" })
set(0, "WinSeparator", { fg = "#587b45", bg = "#f0f5e9" })
set(0, "StatusLine", { fg = "#18301d", bg = "#e5efdc" })
set(0, "StatusLineNC", { fg = "#55705a", bg = "#f0f5e9" })
set(0, "TabLine", { fg = "#55705a", bg = "#f0f5e9" })
set(0, "TabLineFill", { fg = "#55705a", bg = "#f0f5e9" })
set(0, "TabLineSel", { fg = "#f0f5e9", bg = "#2f7d32", bold = true })
set(0, "Visual", { bg = "#d6e5c9" })
set(0, "Search", { fg = "#f0f5e9", bg = "#8a6700" })
set(0, "IncSearch", { fg = "#f0f5e9", bg = "#2f7d32" })
set(0, "Substitute", { fg = "#f0f5e9", bg = "#8a6700" })
set(0, "Pmenu", { fg = "#18301d", bg = "#e5efdc" })
set(0, "PmenuSel", { fg = "#f0f5e9", bg = "#2f7d32" })
set(0, "PmenuSbar", { bg = "#d6e5c9" })
set(0, "PmenuThumb", { bg = "#587b45" })
set(0, "Comment", { fg = "#587b45", italic = true })
set(0, "Constant", { fg = "#8a6700" })
set(0, "String", { fg = "#4e812f" })
set(0, "Character", { fg = "#4e812f" })
set(0, "Number", { fg = "#8a6700" })
set(0, "Boolean", { fg = "#8a6700" })
set(0, "Identifier", { fg = "#18301d" })
set(0, "Function", { fg = "#2f6090" })
set(0, "Statement", { fg = "#2f7d32", bold = true })
set(0, "Conditional", { fg = "#2f7d32", bold = true })
set(0, "Repeat", { fg = "#2f7d32", bold = true })
set(0, "Label", { fg = "#087f78" })
set(0, "Operator", { fg = "#4c8f46" })
set(0, "Keyword", { fg = "#2f7d32", bold = true })
set(0, "Exception", { fg = "#a83b3b" })
set(0, "PreProc", { fg = "#76509d" })
set(0, "Include", { fg = "#76509d" })
set(0, "Define", { fg = "#76509d" })
set(0, "Macro", { fg = "#76509d" })
set(0, "Type", { fg = "#087f78" })
set(0, "StorageClass", { fg = "#087f78" })
set(0, "Structure", { fg = "#087f78" })
set(0, "Typedef", { fg = "#087f78" })
set(0, "Special", { fg = "#087f78" })
set(0, "SpecialComment", { fg = "#587b45" })
set(0, "Error", { fg = "#a83b3b", bold = true })
set(0, "Todo", { fg = "#f0f5e9", bg = "#8a6700", bold = true })
set(0, "DiagnosticError", { fg = "#a83b3b" })
set(0, "DiagnosticWarn", { fg = "#8a6700" })
set(0, "DiagnosticInfo", { fg = "#2f6090" })
set(0, "DiagnosticHint", { fg = "#087f78" })
set(0, "DiffAdd", { fg = "#197a42", bg = "#dcefdc" })
set(0, "DiffDelete", { fg = "#a83b3b", bg = "#f5e1dc" })
set(0, "DiffChange", { fg = "#8a6700", bg = "#e5efdc" })
set(0, "DiffText", { fg = "#f0f5e9", bg = "#8a6700" })
set(0, "GitSignsAdd", { fg = "#197a42" })
set(0, "GitSignsChange", { fg = "#8a6700" })
set(0, "GitSignsDelete", { fg = "#a83b3b" })
set(0, "TelescopeBorder", { fg = "#587b45", bg = "#e5efdc" })
set(0, "TelescopePromptBorder", { fg = "#2f7d32", bg = "#e5efdc" })
set(0, "TelescopeSelection", { fg = "#18301d", bg = "#d6e5c9" })
set(0, "TelescopeMatching", { fg = "#2f7d32", bold = true })
set(0, "WhichKey", { fg = "#2f7d32" })
set(0, "WhichKeyGroup", { fg = "#087f78" })
set(0, "IblIndent", { fg = "#587b45" })
set(0, "DashboardHeader", { fg = "#2f7d32" })
set(0, "DashboardDesc", { fg = "#2f7d32" })
set(0, "DashboardIcon", { fg = "#2f7d32" })
set(0, "DashboardKey", { fg = "#2f7d32" })
set(0, "DashboardFooter", { fg = "#2f7d32" })
set(0, "TroubleText", { fg = "#18301d" })
set(0, "TroubleCount", { fg = "#087f78" })
set(0, "OilDir", { fg = "#2f6090" })
set(0, "BlinkCmpMenu", { fg = "#18301d", bg = "#e5efdc" })
set(0, "BlinkCmpMenuSelection", { fg = "#f0f5e9", bg = "#2f7d32" })
set(0, "@comment", { fg = "#587b45", italic = true })
set(0, "@constant", { fg = "#8a6700" })
set(0, "@string", { fg = "#4e812f" })
set(0, "@number", { fg = "#8a6700" })
set(0, "@boolean", { fg = "#8a6700" })
set(0, "@variable", { fg = "#18301d" })
set(0, "@parameter", { fg = "#18301d" })
set(0, "@function", { fg = "#2f6090" })
set(0, "@function.call", { fg = "#2f6090" })
set(0, "@keyword", { fg = "#2f7d32", bold = true })
set(0, "@keyword.function", { fg = "#2f7d32", bold = true })
set(0, "@type", { fg = "#087f78" })
set(0, "@type.builtin", { fg = "#087f78" })
set(0, "@operator", { fg = "#4c8f46" })
set(0, "@property", { fg = "#087f78" })
set(0, "@tag", { fg = "#2f7d32" })
set(0, "@tag.attribute", { fg = "#087f78" })

vim.g.terminal_color_0 = "#18301d"
vim.g.terminal_color_1 = "#a83b3b"
vim.g.terminal_color_2 = "#4c8f46"
vim.g.terminal_color_3 = "#8a6700"
vim.g.terminal_color_4 = "#2f6090"
vim.g.terminal_color_5 = "#76509d"
vim.g.terminal_color_6 = "#087f78"
vim.g.terminal_color_7 = "#304e35"
vim.g.terminal_color_8 = "#55705a"
vim.g.terminal_color_9 = "#c25252"
vim.g.terminal_color_10 = "#2f7d32"
vim.g.terminal_color_11 = "#a47e00"
vim.g.terminal_color_12 = "#4a7ead"
vim.g.terminal_color_13 = "#9369bd"
vim.g.terminal_color_14 = "#1a9c93"
vim.g.terminal_color_15 = "#18301d"
