-- Generated by scripts/theme.ts from themes/nord/.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "light"
vim.g.colors_name = "nord-light"

local set = vim.api.nvim_set_hl

set(0, "Normal", { fg = "#2e3440", bg = "#eceff4" })
set(0, "NormalFloat", { fg = "#2e3440", bg = "#e5e9f0" })
set(0, "NormalNC", { fg = "#2e3440", bg = "#eceff4" })
set(0, "Cursor", { fg = "#eceff4", bg = "#5e81ac" })
set(0, "CursorLine", { bg = "#e5e9f0" })
set(0, "CursorLineNr", { fg = "#5e81ac", bg = "#e5e9f0", bold = true })
set(0, "LineNr", { fg = "#4c566a" })
set(0, "SignColumn", { fg = "#5e81ac", bg = "#eceff4" })
set(0, "FoldColumn", { fg = "#5e81ac", bg = "#eceff4" })
set(0, "WinSeparator", { fg = "#5e81ac", bg = "#eceff4" })
set(0, "StatusLine", { fg = "#2e3440", bg = "#e5e9f0" })
set(0, "StatusLineNC", { fg = "#4c566a", bg = "#eceff4" })
set(0, "TabLine", { fg = "#4c566a", bg = "#eceff4" })
set(0, "TabLineFill", { fg = "#4c566a", bg = "#eceff4" })
set(0, "TabLineSel", { fg = "#eceff4", bg = "#5e81ac", bold = true })
set(0, "Visual", { bg = "#d8dee9" })
set(0, "Search", { fg = "#eceff4", bg = "#9a6b00" })
set(0, "IncSearch", { fg = "#eceff4", bg = "#5e81ac" })
set(0, "Substitute", { fg = "#eceff4", bg = "#9a6b00" })
set(0, "Pmenu", { fg = "#2e3440", bg = "#e5e9f0" })
set(0, "PmenuSel", { fg = "#eceff4", bg = "#5e81ac" })
set(0, "PmenuSbar", { bg = "#d8dee9" })
set(0, "PmenuThumb", { bg = "#5e81ac" })
set(0, "Comment", { fg = "#5e81ac", italic = true })
set(0, "Constant", { fg = "#9a6b00" })
set(0, "String", { fg = "#4d7a47" })
set(0, "Character", { fg = "#4d7a47" })
set(0, "Number", { fg = "#9a6b00" })
set(0, "Boolean", { fg = "#9a6b00" })
set(0, "Identifier", { fg = "#2e3440" })
set(0, "Function", { fg = "#5e81ac" })
set(0, "Statement", { fg = "#5e81ac", bold = true })
set(0, "Conditional", { fg = "#5e81ac", bold = true })
set(0, "Repeat", { fg = "#5e81ac", bold = true })
set(0, "Label", { fg = "#3b7d8f" })
set(0, "Operator", { fg = "#4c7a8a" })
set(0, "Keyword", { fg = "#5e81ac", bold = true })
set(0, "Exception", { fg = "#a33f4a" })
set(0, "PreProc", { fg = "#8f6a8f" })
set(0, "Include", { fg = "#8f6a8f" })
set(0, "Define", { fg = "#8f6a8f" })
set(0, "Macro", { fg = "#8f6a8f" })
set(0, "Type", { fg = "#3b7d8f" })
set(0, "StorageClass", { fg = "#3b7d8f" })
set(0, "Structure", { fg = "#3b7d8f" })
set(0, "Typedef", { fg = "#3b7d8f" })
set(0, "Special", { fg = "#3b7d8f" })
set(0, "SpecialComment", { fg = "#5e81ac" })
set(0, "Error", { fg = "#a33f4a", bold = true })
set(0, "Todo", { fg = "#eceff4", bg = "#9a6b00", bold = true })
set(0, "DiagnosticError", { fg = "#a33f4a" })
set(0, "DiagnosticWarn", { fg = "#9a6b00" })
set(0, "DiagnosticInfo", { fg = "#5e81ac" })
set(0, "DiagnosticHint", { fg = "#3b7d8f" })
set(0, "DiffAdd", { fg = "#477a50", bg = "#dfeee4" })
set(0, "DiffDelete", { fg = "#a33f4a", bg = "#f2dfe2" })
set(0, "DiffChange", { fg = "#9a6b00", bg = "#e5e9f0" })
set(0, "DiffText", { fg = "#eceff4", bg = "#9a6b00" })
set(0, "GitSignsAdd", { fg = "#477a50" })
set(0, "GitSignsChange", { fg = "#9a6b00" })
set(0, "GitSignsDelete", { fg = "#a33f4a" })
set(0, "TelescopeBorder", { fg = "#5e81ac", bg = "#e5e9f0" })
set(0, "TelescopePromptBorder", { fg = "#5e81ac", bg = "#e5e9f0" })
set(0, "TelescopeSelection", { fg = "#2e3440", bg = "#d8dee9" })
set(0, "TelescopeMatching", { fg = "#5e81ac", bold = true })
set(0, "WhichKey", { fg = "#5e81ac" })
set(0, "WhichKeyGroup", { fg = "#3b7d8f" })
set(0, "IblIndent", { fg = "#5e81ac" })
set(0, "DashboardHeader", { fg = "#5e81ac" })
set(0, "DashboardDesc", { fg = "#5e81ac" })
set(0, "DashboardIcon", { fg = "#5e81ac" })
set(0, "DashboardKey", { fg = "#5e81ac" })
set(0, "DashboardFooter", { fg = "#5e81ac" })
set(0, "TroubleText", { fg = "#2e3440" })
set(0, "TroubleCount", { fg = "#3b7d8f" })
set(0, "OilDir", { fg = "#5e81ac" })
set(0, "BlinkCmpMenu", { fg = "#2e3440", bg = "#e5e9f0" })
set(0, "BlinkCmpMenuSelection", { fg = "#eceff4", bg = "#5e81ac" })
set(0, "@comment", { fg = "#5e81ac", italic = true })
set(0, "@constant", { fg = "#9a6b00" })
set(0, "@string", { fg = "#4d7a47" })
set(0, "@number", { fg = "#9a6b00" })
set(0, "@boolean", { fg = "#9a6b00" })
set(0, "@variable", { fg = "#2e3440" })
set(0, "@parameter", { fg = "#2e3440" })
set(0, "@function", { fg = "#5e81ac" })
set(0, "@function.call", { fg = "#5e81ac" })
set(0, "@keyword", { fg = "#5e81ac", bold = true })
set(0, "@keyword.function", { fg = "#5e81ac", bold = true })
set(0, "@type", { fg = "#3b7d8f" })
set(0, "@type.builtin", { fg = "#3b7d8f" })
set(0, "@operator", { fg = "#4c7a8a" })
set(0, "@property", { fg = "#3b7d8f" })
set(0, "@tag", { fg = "#5e81ac" })
set(0, "@tag.attribute", { fg = "#3b7d8f" })

vim.g.terminal_color_0 = "#2e3440"
vim.g.terminal_color_1 = "#a33f4a"
vim.g.terminal_color_2 = "#477a50"
vim.g.terminal_color_3 = "#9a6b00"
vim.g.terminal_color_4 = "#5e81ac"
vim.g.terminal_color_5 = "#8f6a8f"
vim.g.terminal_color_6 = "#3b7d8f"
vim.g.terminal_color_7 = "#4c566a"
vim.g.terminal_color_8 = "#4c566a"
vim.g.terminal_color_9 = "#bf616a"
vim.g.terminal_color_10 = "#5c9860"
vim.g.terminal_color_11 = "#b17d00"
vim.g.terminal_color_12 = "#81a1c1"
vim.g.terminal_color_13 = "#b48ead"
vim.g.terminal_color_14 = "#4f9aaa"
vim.g.terminal_color_15 = "#2e3440"
