-- Generated by scripts/theme.ts from themes/nord/.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "nord-dark"

local set = vim.api.nvim_set_hl

set(0, "Normal", { fg = "#eceff4", bg = "#2e3440" })
set(0, "NormalFloat", { fg = "#eceff4", bg = "#3b4252" })
set(0, "NormalNC", { fg = "#eceff4", bg = "#2e3440" })
set(0, "Cursor", { fg = "#2e3440", bg = "#88c0d0" })
set(0, "CursorLine", { bg = "#3b4252" })
set(0, "CursorLineNr", { fg = "#88c0d0", bg = "#3b4252", bold = true })
set(0, "LineNr", { fg = "#4c566a" })
set(0, "SignColumn", { fg = "#616e82", bg = "#2e3440" })
set(0, "FoldColumn", { fg = "#616e82", bg = "#2e3440" })
set(0, "WinSeparator", { fg = "#616e82", bg = "#2e3440" })
set(0, "StatusLine", { fg = "#eceff4", bg = "#3b4252" })
set(0, "StatusLineNC", { fg = "#4c566a", bg = "#2e3440" })
set(0, "TabLine", { fg = "#4c566a", bg = "#2e3440" })
set(0, "TabLineFill", { fg = "#4c566a", bg = "#2e3440" })
set(0, "TabLineSel", { fg = "#2e3440", bg = "#88c0d0", bold = true })
set(0, "Visual", { bg = "#434c5e" })
set(0, "Search", { fg = "#2e3440", bg = "#ebcb8b" })
set(0, "IncSearch", { fg = "#2e3440", bg = "#88c0d0" })
set(0, "Substitute", { fg = "#2e3440", bg = "#ebcb8b" })
set(0, "Pmenu", { fg = "#eceff4", bg = "#3b4252" })
set(0, "PmenuSel", { fg = "#2e3440", bg = "#88c0d0" })
set(0, "PmenuSbar", { bg = "#434c5e" })
set(0, "PmenuThumb", { bg = "#616e82" })
set(0, "Comment", { fg = "#616e82", italic = true })
set(0, "Constant", { fg = "#ebcb8b" })
set(0, "String", { fg = "#a3be8c" })
set(0, "Character", { fg = "#a3be8c" })
set(0, "Number", { fg = "#ebcb8b" })
set(0, "Boolean", { fg = "#ebcb8b" })
set(0, "Identifier", { fg = "#eceff4" })
set(0, "Function", { fg = "#81a1c1" })
set(0, "Statement", { fg = "#88c0d0", bold = true })
set(0, "Conditional", { fg = "#88c0d0", bold = true })
set(0, "Repeat", { fg = "#88c0d0", bold = true })
set(0, "Label", { fg = "#8fbcbb" })
set(0, "Operator", { fg = "#8fbcbb" })
set(0, "Keyword", { fg = "#88c0d0", bold = true })
set(0, "Exception", { fg = "#bf616a" })
set(0, "PreProc", { fg = "#b48ead" })
set(0, "Include", { fg = "#b48ead" })
set(0, "Define", { fg = "#b48ead" })
set(0, "Macro", { fg = "#b48ead" })
set(0, "Type", { fg = "#8fbcbb" })
set(0, "StorageClass", { fg = "#8fbcbb" })
set(0, "Structure", { fg = "#8fbcbb" })
set(0, "Typedef", { fg = "#8fbcbb" })
set(0, "Special", { fg = "#8fbcbb" })
set(0, "SpecialComment", { fg = "#616e82" })
set(0, "Error", { fg = "#bf616a", bold = true })
set(0, "Todo", { fg = "#2e3440", bg = "#ebcb8b", bold = true })
set(0, "DiagnosticError", { fg = "#bf616a" })
set(0, "DiagnosticWarn", { fg = "#ebcb8b" })
set(0, "DiagnosticInfo", { fg = "#81a1c1" })
set(0, "DiagnosticHint", { fg = "#8fbcbb" })
set(0, "DiffAdd", { fg = "#a3be8c", bg = "#35464b" })
set(0, "DiffDelete", { fg = "#bf616a", bg = "#4b343a" })
set(0, "DiffChange", { fg = "#ebcb8b", bg = "#3b4252" })
set(0, "DiffText", { fg = "#2e3440", bg = "#ebcb8b" })
set(0, "GitSignsAdd", { fg = "#a3be8c" })
set(0, "GitSignsChange", { fg = "#ebcb8b" })
set(0, "GitSignsDelete", { fg = "#bf616a" })
set(0, "TelescopeBorder", { fg = "#616e82", bg = "#3b4252" })
set(0, "TelescopePromptBorder", { fg = "#88c0d0", bg = "#3b4252" })
set(0, "TelescopeSelection", { fg = "#eceff4", bg = "#434c5e" })
set(0, "TelescopeMatching", { fg = "#88c0d0", bold = true })
set(0, "WhichKey", { fg = "#88c0d0" })
set(0, "WhichKeyGroup", { fg = "#8fbcbb" })
set(0, "IblIndent", { fg = "#616e82" })
set(0, "DashboardHeader", { fg = "#88c0d0" })
set(0, "DashboardDesc", { fg = "#88c0d0" })
set(0, "DashboardIcon", { fg = "#88c0d0" })
set(0, "DashboardKey", { fg = "#88c0d0" })
set(0, "DashboardFooter", { fg = "#88c0d0" })
set(0, "TroubleText", { fg = "#eceff4" })
set(0, "TroubleCount", { fg = "#8fbcbb" })
set(0, "OilDir", { fg = "#81a1c1" })
set(0, "BlinkCmpMenu", { fg = "#eceff4", bg = "#3b4252" })
set(0, "BlinkCmpMenuSelection", { fg = "#2e3440", bg = "#88c0d0" })
set(0, "@comment", { fg = "#616e82", italic = true })
set(0, "@constant", { fg = "#ebcb8b" })
set(0, "@string", { fg = "#a3be8c" })
set(0, "@number", { fg = "#ebcb8b" })
set(0, "@boolean", { fg = "#ebcb8b" })
set(0, "@variable", { fg = "#eceff4" })
set(0, "@parameter", { fg = "#eceff4" })
set(0, "@function", { fg = "#81a1c1" })
set(0, "@function.call", { fg = "#81a1c1" })
set(0, "@keyword", { fg = "#88c0d0", bold = true })
set(0, "@keyword.function", { fg = "#88c0d0", bold = true })
set(0, "@type", { fg = "#8fbcbb" })
set(0, "@type.builtin", { fg = "#8fbcbb" })
set(0, "@operator", { fg = "#8fbcbb" })
set(0, "@property", { fg = "#8fbcbb" })
set(0, "@tag", { fg = "#88c0d0" })
set(0, "@tag.attribute", { fg = "#8fbcbb" })

vim.g.terminal_color_0 = "#2e3440"
vim.g.terminal_color_1 = "#bf616a"
vim.g.terminal_color_2 = "#a3be8c"
vim.g.terminal_color_3 = "#ebcb8b"
vim.g.terminal_color_4 = "#81a1c1"
vim.g.terminal_color_5 = "#b48ead"
vim.g.terminal_color_6 = "#88c0d0"
vim.g.terminal_color_7 = "#e5e9f0"
vim.g.terminal_color_8 = "#4c566a"
vim.g.terminal_color_9 = "#bf616a"
vim.g.terminal_color_10 = "#a3be8c"
vim.g.terminal_color_11 = "#ebcb8b"
vim.g.terminal_color_12 = "#81a1c1"
vim.g.terminal_color_13 = "#b48ead"
vim.g.terminal_color_14 = "#8fbcbb"
vim.g.terminal_color_15 = "#eceff4"
